Import("env", "libraryPath", "localBinInstall", "getLibraries")

localLibraries = getLibraries(["CGIPLUS"])
localLibraries.extend(["boost_unit_test_framework"])

cgiTest = env.Program("cgiTest", ["CgiTest.cpp"], 
                      LIBS = localLibraries, LIBPATH = libraryPath)

env.Test("cgi.passed", cgiTest)
