# This file is part of CGIplus.
#
# CGIplus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CGIplus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CGIplus.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

Import("env", "basePath", "localLibraryInstall")

sys.path.append(basePath + "/install")
import installer

cgiplusName = localLibraryInstall + "/" + os.getcwd().split("/")[-1]
cgiplusLib = env.StaticLibrary(cgiplusName, Glob("*.cpp"))

opts = Variables(basePath + "/conf/cgiplus.conf", ARGUMENTS)
installer.AddOptions(opts)
opts.Update(env)

install = installer.Installer(env)
install.AddLibrary(cgiplusLib)
install.AddHeaders(basePath + "/include/cgiplus/", "*.hpp")
