import os
import sys

Import("env", "basePath", "localLibraryInstall")

sys.path.append(basePath + "/install")
import installer

cgiplusName = localLibraryInstall + "/" + os.getcwd().split("/")[-1]
cgiplusLib = env.StaticLibrary(cgiplusName, Glob("*.cpp"))

opts = Variables(basePath + "/conf/cgiplus.conf", ARGUMENTS)
installer.AddOptions(opts)
opts.Update(env)

install = installer.Installer(env)
install.AddLibrary(cgiplusLib)
install.AddHeaders(basePath + "/include/cgiplus/", "*.hpp")
