import os
import installer

Import("env", "basePath", "localLibraryInstall")

cgiplusName = localLibraryInstall + "/" + os.getcwd().split("/")[-1]
cgiplusLib = env.StaticLibrary(cgiplusName, Glob("*.cpp"))

opts = Variables(basePath + "/cgiplus.conf", ARGUMENTS)
installer.AddOptions(opts)
opts.Update(env)

install = installer.Installer(env)
install.AddLibrary(cgiplusLib)
install.AddHeaders(basePath + "/include/cgiplus/", "*.hpp")
